import { CircleHelp, RefreshCw, Sparkles } from 'lucide-react';
import type { Analysis } from './types';

export function AnalysisPanel({ analysis, onAnalyze }: { analysis: Analysis | null; onAnalyze: () => void }) {
  if (!analysis) return <section className="control-section"><Sparkles size={26}/><h3>Узнать больше о кадре</h3><p className="control-note">Резкость, экспозиция, композиция и положение лица оцениваются отдельно.</p><button className="button primary full" onClick={onAnalyze}>Анализировать</button></section>;
  const names:Record<string,string>={clip:'сравнение содержания',aesthetic:'эстетическая оценка',face:'анализ лиц',pose:'анализ позы',skin:'маска кожи'};
  const unavailable=Object.keys(names).filter(name=>!analysis.models?.[name] || !!analysis.model_errors?.[name]);
  return <>{unavailable.length>0 && <section className="control-section"><h3>Ограничения ИИ</h3><p className="control-note">Недоступны: {unavailable.map(name=>names[name]).join(', ')}. Часть анализа и ретуши пропущена. Проверьте модели в настройках.</p>{Object.entries(analysis.model_errors || {}).map(([name,error])=><p className="error-text" key={name}>{names[name] || name}: {error}</p>)}</section>}<section className="control-section"><h3>Оценка кадра <span>{analysis.source === 'developed' ? 'ПОСЛЕ ПРОЯВКИ' : 'ПРЕВЬЮ'}</span></h3><div className="large-score">{(analysis.score * 10).toFixed(1)}<small>/ 10</small></div>{[['Техническое качество',analysis.technical],['Композиция',analysis.composition.score],['Света без клиппинга',1-analysis.highlight_clipping]].map(([label, value]) => <div className="metric" key={label as string}><span>{label}<b>{Math.round((value as number)*100)}%</b></span><i><b style={{width:`${(value as number)*100}%`}}/></i></div>)}</section><section className="control-section"><h3>Что проверить</h3>{analysis.notes.map((note, i) => <p className="analysis-note" key={i}><CircleHelp size={14}/>{note}</p>)}{!analysis.notes.length && <p className="control-note">Явных поводов для проверки не найдено. Финальное решение остаётся за вами.</p>}</section><section className="control-section"><h3>Лица <span>{analysis.faces.length}</span></h3>{analysis.faces.map((f,i) => <div className="face-info" key={i}><b>Лицо {i+1}</b><span>{f.eyes_closed > .65 ? 'Возможно закрыты глаза' : 'Глаза, вероятно, открыты'}</span><small>Резкость: {f.sharpness?.toFixed(2) || '—'}</small></div>)}<button className="button full" onClick={onAnalyze}><RefreshCw size={14}/> Повторить анализ</button></section></>;
}
